# Generated by Django 3.0 on 2020-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_blog',
            name='image',
            field=models.ImageField(upload_to='media/blog/images/'),
        ),
    ]
