# Generated by Django 3.0 on 2020-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200516_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_blog',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
