# Generated by Django 3.0 on 2020-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200516_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_blog',
            name='date',
            field=models.DateField(),
        ),
    ]
